### ISSUE TITLE
Cannot install requirement

### ISSUE THREAD

**Issue by holywend** [cbrussell/cryptid-generation#2]
After running 
pip install -r requirements.txt
I run into an error
![image](https://user-images.githubusercontent.com/20583849/176199409-91dfbafd-fdad-4972-a78e-d91abb3b1c21.png)

**Comment by holywend** [comment]
Great. thanks for looking into this.

**Comment by cbrussell** [comment]
Issue is resolved. Only numpy and pillow are required.
