### ISSUE TITLE
Example assets

### ISSUE THREAD

**Issue by holywend** [cbrussell/cryptid-generation#3]
Do you mind to provide a sample source images, im not pretty sure how the script work out yet. Tbh, i dont know any python, but your work here is superb (I see your generated example on reddit)

**Comment by cbrussell** [comment]
Hey - I'd prefer to let the user provide their own source files. Are you stuck on something?

**Comment by holywend** [comment]
Ok where do I need to create the assets folder and what kind of images is acceptable png transparent background? then what files do I need to change to adjust my assets? thx

**Comment by cbrussell** [comment]
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/3781295/176694820-bdb5f9c2-ee0d-4f79-afee-4caf27512802.png">
Hopefully this helps.

**Comment by holywend** [comment]
whoa, that certainly gave me lots of ideas thx.
